.PHONY: run
run: Main.class AFB.class AFBResult.class AFB_TSP.class
	java Main

Main.class: Main.java
	javac Main.java

AFB.class: AFB.java
	javac AFB.java

AFBResult.class: AFBResult.java
	javac AFBResult.java

AFB_TSP.class: AFB_TSP.java
	javac AFB_TSP.java
